language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - tools
    - platform-tools-24.1.1
    - build-tools-24.0.1
    - android-24
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  - chmod +x gradlew
  
script:
   - ./gradlew clean
