language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - tools
    - platform-tools-25.0.3
    - build-tools-25.0.2
    - android-25
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  - chmod +x gradlew
  
script:
   - ./gradlew clean
