language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.3
    - android-23
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

script:
   - ./gradlew build assembleDebug
