language: android

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    
before_install:
 - chmod +x gradlew
